# Generated by Django 5.2.11 on 2026-03-03 15:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='average_rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='country_of_origin',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='delivery_info',
            field=models.CharField(blank=True, default='Free Delivery in 3-5 business days', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='generic_name',
            field=models.CharField(blank=True, help_text='Common name of product, e.g., Smartphone, Shirt', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='highlights',
            field=models.TextField(blank=True, help_text='Key features, separate with newlines for bullet points'),
        ),
        migrations.AddField(
            model_name='product',
            name='hsn_code',
            field=models.CharField(blank=True, help_text='Harmonized System of Nomenclature code for tax', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='importer_details',
            field=models.TextField(blank=True, help_text='Name and Address of Importer', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='is_bestseller',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='is_new',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='manufacturer_details',
            field=models.TextField(blank=True, help_text='Name and Address of Manufacturer', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='model_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='model_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='net_quantity',
            field=models.CharField(blank=True, help_text='e.g., 1 unit, 500g, 10 pieces', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='packer_details',
            field=models.TextField(blank=True, help_text='Name and Address of Packer', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_dimensions',
            field=models.CharField(blank=True, help_text='e.g., 15 x 7 x 0.8 cm', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_weight',
            field=models.CharField(blank=True, help_text='Weight including unit, e.g., 200g', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='replacement_policy',
            field=models.CharField(blank=True, default='7-Day Replacement Policy', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='return_days',
            field=models.PositiveIntegerField(default=7),
        ),
        migrations.AddField(
            model_name='product',
            name='return_policy',
            field=models.CharField(blank=True, default='7-Day Return Policy', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='review_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, help_text='Stock Keeping Unit', max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='product',
            name='specifications',
            field=models.JSONField(blank=True, default=dict, help_text='Store technical specs as key-value pairs'),
        ),
        migrations.AddField(
            model_name='product',
            name='video_url',
            field=models.URLField(blank=True, help_text='URL for product demo video', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='warranty_covered',
            field=models.TextField(blank=True, help_text='What is covered? (Manufacturing defects, etc.)', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='warranty_not_covered',
            field=models.TextField(blank=True, help_text='What is NOT covered? (Physical damage, etc.)', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='warranty_period',
            field=models.CharField(blank=True, help_text='e.g., 12 Months', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='warranty_service_type',
            field=models.TextField(blank=True, help_text='e.g., On-site or Carry-in', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='warranty_summary',
            field=models.CharField(blank=True, help_text='Short warranty string, e.g., 1 Year Manufacturer Warranty', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='productimage',
            name='alt_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='productimage',
            name='is_feature_image',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(help_text='Detailed product description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., XL Silver, 8GB RAM / 128GB Storage', max_length=100)),
                ('sku', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='Override base product price if needed', max_digits=12, null=True)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('image', models.ImageField(blank=True, help_text='Variant specific image (optional)', null=True, upload_to='variants/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='app.product')),
            ],
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('products', models.ManyToManyField(blank=True, related_name='wishlisted_by', to='app.product')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('comment', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='reviews/')),
                ('is_verified_purchase', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='app.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('product', 'user')},
            },
        ),
    ]
