# Generated by Django 5.2.11 on 2026-03-03 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_product_average_rating_product_brand_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='full_name',
        ),
    ]
